spring.application.name=System
# Database URL
spring.datasource.url=jdbc:postgresql://ep-snowy-mouse-a1ar21g8-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require

# Credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Omi2L6XTqNYy

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (important)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional (logs SQL)
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=royajay6291@gmail.com
spring.mail.password=tajd fsmo rtof bqis

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true